language: node_js
nodejs:
  - 8

script:
  - npm run ci

notifications:
  email:
    recipients:
      - secure: "KIMIWh2dlRXMnfnrWJc0AlxZQlawl1bB4ABWduIxgPmOZw9SRDLGjUoDNwtmnKFi6hYgTayNyYQNycvOhz0xuFwVOMo8Yg6WQg/TkRB2Vecm7/p/zu3eVBCRjVLPGmF64byI1B1JHay3k4DYVSoqhsWwRVwGU7NJd5ZQoT5/9vfZX4V68QeHK2Mxn1b2cPWGnlwIHBMQjHrjzg6W/F77AVln7hBsRbFmD7rbuXLaOYYAoyBUx9fXI/0VqwtL6AvtCF0dX8Ig8HAceovhN5Retmcrx5bYjOlZqGGxGpfyiNEAdNlVkp+OQ8CxDmM5x4hm1lkuVkfYCZct8X33JgIUjmmpmpbu/58Oz048CgQ/XfURZz0z1OuxhdqM0hQzn710dpwwjToFdlDuTFY9k/BOpup7cgFJ2UeJvi1SqFe1bCmiH5tqBiAbwu8RBXY106HHzziI0AAt6vWkJ58SqQgQjatzsVoh6jJBsuCi2cXVC4eoiAxX8LFgvaCDcNIBbxpwZPJYPRz8lgyXSoQYnC41kGA4CxOpwfpeyLxb8ymWdaddnfNtfNVh8tPZ5LGQ2HWAl6qHTfpduR9e/D6fEu9zHsPRFA5H5FK8FY1o74q/AaizAZ9sdCeuTyPC+gXFwf3QCyJMS/amBwjpQm54T5aeupNYWxPpKvL+SmUAoVZqxio="
