language: node_js
nodejs:
- 10

script:
- npm run ci

notifications:
  email:
    recipients:
    - secure: jW0jfiF1VT6Eb6pcr/2mmMchVeKaPd18h1mpLWdAaeSJjMnhn+5ooNpWZFtxnJhrE1ebTyN429kjRKHaL9tb37j7E459jOl59miTy8RSPKuCpuEm4HtSNbd+mAZASdmSOVwncGPjgZEGtVUPHclFEhjlajo9H38rUCj5DJWsmu3PuIjRv7RM52mp+GsFCUiDfzlcjMRW1PRNdpGz0F8IK6ItKx3i6CpCCVeuEO6E+XkyuH9FmRPkZ293GggoJ7LdNje8DAZSPCLtpZ9l99YZ6d0Lbsi33lTQobtyFvwrc1PUhfGNKppXC4YqTNqcwxMkBuPX80uyVYXk/5hW7wRMPZ08246iRnHB1q4b15eHi+Bf/BIlnsCJ7nTeZyoPDeVkWIvJXZSloEwFR9lkStPXujvK1QVtAk1boWN1phxppBElY2LSPOjM983SRd0fQdAZ0xIBpYtHc/3jDvC4/q4lh6R69CMxYCs/krOK7KBrOVWTXM1SQDzQjU042RyU1YFD0fuqUJhk7OVBrIiArf31ecu+aRp583OuxaLD9bfpazovmKBuWKtFmkMAA6ZlNhRS2u1nvGdKvUGl0BW2jXZAh6CF4urh7p3tfPpXQqYbbvEd51mwjJt/grUigZTaPJZXInBKjZFnll3Q2Eo84mtpxPSt/QjMqJ9Qy9ayJM8DMdc=
